version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=not-pintenterest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abobus
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d not-pintenterest"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    restart: always
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=abobus
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=not-pintenterest
    volumes:
      - ./assets:/app/assets
    ports:
      - 8010:8000
