from backend.schemas.error import AUTH_REQUIRED, HTTP_401_UNAUTHORIZED, USER_NOT_FOUND, NOT_ENOUGH_RIGHTS_403, IDEA_WITH_THIS_NAME_ALREADY_EXISTS
from fastapi import status
UNAUTHORIZED_401 = {status.HTTP_401_UNAUTHORIZED: {
    "model": HTTP_401_UNAUTHORIZED}}

NOT_FOUND_USER = {status.HTTP_404_NOT_FOUND: {"model": USER_NOT_FOUND}}
NOT_ENOUGH_RIGHTS = {status.HTTP_403_FORBIDDEN: {
    "model": NOT_ENOUGH_RIGHTS_403}}
AUTH_REQUIRED_401 = {status.HTTP_401_UNAUTHORIZED: {
    "model": AUTH_REQUIRED}}
IDEA_WITH_THIS_NAME_ALREADY_EXISTS_400 = {status.HTTP_400_BAD_REQUEST: {
    "model": IDEA_WITH_THIS_NAME_ALREADY_EXISTS}}
