"""upd

Revision ID: 5c1bcdd45ba5
Revises: df6967fa9760
Create Date: 2022-12-02 12:58:26.899585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1bcdd45ba5'
down_revision = 'df6967fa9760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
