"""fix?

Revision ID: 901632f61e47
Revises: 5c1bcdd45ba5
Create Date: 2023-01-24 17:32:07.603782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901632f61e47'
down_revision = '5c1bcdd45ba5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
