"""added keywords+

Revision ID: 9253a8c96f12
Revises: 47e9e77c360c
Create Date: 2023-02-13 20:18:59.031741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9253a8c96f12'
down_revision = '47e9e77c360c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'keyword_id')
    )
    op.add_column('keywords', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.add_column('posts_keywords', sa.Column('keyword_id', sa.Integer(), nullable=False))
    op.drop_constraint('posts_keywords_keyword_fkey', 'posts_keywords', type_='foreignkey')
    op.create_foreign_key(None, 'posts_keywords', 'keywords', ['keyword_id'], ['id'])
    op.drop_column('posts_keywords', 'keyword')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts_keywords', sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts_keywords', type_='foreignkey')
    op.create_foreign_key('posts_keywords_keyword_fkey', 'posts_keywords', 'keywords', ['keyword'], ['name'])
    op.drop_column('posts_keywords', 'keyword_id')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_column('keywords', 'id')
    op.drop_table('keywords_likes')
    # ### end Alembic commands ###
