"""cganged post table

Revision ID: 9364bbc5f4b2
Revises: 
Create Date: 2023-02-06 20:55:55.716568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9364bbc5f4b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'idea_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('posts_idea_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'ideas', ['idea_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_idea_id_fkey', 'posts', 'ideas', ['idea_id'], ['id'])
    op.alter_column('posts', 'idea_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
