"""cascade delete images

Revision ID: b6af8411168f
Revises: bd226e96da5e
Create Date: 2023-01-28 12:29:13.977958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6af8411168f'
down_revision = 'bd226e96da5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
