"""added cascade delete to posts tables

Revision ID: bd226e96da5e
Revises: 8af17372a3e6
Create Date: 2023-01-28 12:17:54.442745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd226e96da5e'
down_revision = '8af17372a3e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
